Added solution for lection 3 (Modal)
js-tasks-ru/htmlcss-20220811_cranch pull request #10
Opened 2022-08-24 09:58 UTC by cranch42

2022-08-24 09:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-24 14:27 UTC, GSemikozov requested changes

2022-08-24 14:27 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +                <div class="modal__title">Modal title</div>
по макету здесь семантический тег заголовка

2022-08-24 14:27 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +                <div class="modal__body">
здесь параграф

2022-08-24 14:27 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +                <div  id="modal-close" class="modal__icon-close">
а здесь - кнопка

2022-08-24 14:27 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    max-width: 348px;
лишнее ограничение

2022-08-24 14:31 UTC, cranch42 commented on 05-lection3/02-modal/modal.css
> +    max-width: 348px;
Без ограничения текст будет во всю ширину, хотя на примере у нас текст шириной 348 пикселей, как быть?

2022-08-24 14:35 UTC, cranch42 commented on 05-lection3/02-modal/index.html
> +                <div class="modal__title">Modal title</div>
В макете отсутствует привязка к стилю заголовка и значения font-size / line-height не совпадают ни с одним из стилей заголовков.

2022-08-24 14:40 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    max-width: 348px;
<img width="476" alt="Screenshot 2022-08-24 at 17 40 17" src="https://user-images.githubusercontent.com/6191270/186447504-d40b67e1-2170-4903-b497-7ca9d5c4bd02.png">
просто паддинги как в макете

2022-08-24 14:40 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +                <div class="modal__title">Modal title</div>
правильнее добавить h3 / h4, но - поскольку в дизайне не указано, не буду настаивать)

2022-08-24 14:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-24 14:51 UTC, GSemikozov requested changes

2022-08-24 14:51 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
и все же fixed )

2022-08-24 14:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-25 12:16 UTC, GSemikozov approved these changes

2022-08-25 12:16 UTC, merged