Added solution for lection 4 (Adaptive Layout)
js-tasks-ru/htmlcss-20220811_cranch pull request #15
Opened 2022-08-28 07:32 UTC by cranch42

2022-08-28 07:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-29 15:44 UTC, GSemikozov requested changes

2022-08-29 15:44 UTC, GSemikozov commented on components/card/card.css
> +    .card__image {
пришло время: это не картинка, а настоящий компонент, мы его должны встроить в карточку (один из способов научиться переиспользовать компоненты).

2022-08-30 04:52 UTC, cranch42 commented on components/card/card.css
> +    .card__image {
Может это лучше сделать после 6 лекции, когда будем переписывать css?

2022-08-30 14:01 UTC, GSemikozov commented on components/card/card.css
> +    .card__image {
моно и так

2022-08-30 14:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-30 14:28 UTC, GSemikozov approved these changes

2022-08-30 14:28 UTC, merged