Added solution for lection 4 (SVG Sprite)
js-tasks-ru/htmlcss-20220811_cranch pull request #16
Opened 2022-08-28 08:08 UTC by cranch42

2022-08-28 08:08 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-29 15:43 UTC, GSemikozov requested changes

2022-08-29 15:43 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item[open] .icon {
.accordion__icon

2022-08-29 15:43 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item[open] .icon {
надо использовать микс

2022-08-29 15:43 UTC, GSemikozov commented on components/icon/icon.css
> +.icon-sm {
.icon_sm

2022-08-30 04:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-30 14:01 UTC, GSemikozov approved these changes

2022-08-30 14:01 UTC, merged