Added main page (initial layout)
js-tasks-ru/htmlcss-20220811_cranch pull request #4
Opened 2022-08-17 21:19 UTC by cranch42

2022-08-17 21:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-18 07:39 UTC, GSemikozov requested changes

2022-08-18 07:39 UTC, GSemikozov commented on assets/css/main.css
>  * {
здесь вообще лучше не использовать `*`

2022-08-18 07:39 UTC, GSemikozov commented on components/page/page.css
> +.header {
страница состоит из отдельных блоков - header, footer, wrapper, поэтому их и надо оформить как отдельные блоки, а не описывать в одном файле

2022-08-18 08:05 UTC, cranch42 commented on assets/css/main.css
>  * {
Просто присвоить шрифт body?
Это правило было изначально просто)

2022-08-18 08:06 UTC, cranch42 commented on components/page/page.css
> +.header {
То есть оформляем блоки в header.css, footer.css, а потом импортим в page.css?

2022-08-18 11:54 UTC, GSemikozov commented on assets/css/main.css
>  * {
да, шрифт общий можно задать на body

2022-08-18 11:54 UTC, GSemikozov commented on components/page/page.css
> +.header {
в page не надо, у нас уже есть общий main.css

2022-08-18 12:09 UTC, cranch42 commented on assets/css/main.css
>  * {
А как быть с box-sizing, задавать каждому компоненту по отдельности?

2022-08-18 12:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-18 12:49 UTC, GSemikozov commented on assets/css/main.css
>  * {
задавать либо при необходимости, либо на уровне глобальных сбросов всем элементам сразу (первый вариант более предпочтительный)

2022-08-18 14:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-08-18 14:40 UTC, GSemikozov approved these changes

2022-08-18 14:40 UTC, merged