Updated layout for lection 2
js-tasks-ru/htmlcss-20220811_cranch pull request #5
Opened 2022-08-21 01:46 UTC by cranch42

2022-08-21 01:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-22 08:14 UTC, GSemikozov requested changes

2022-08-22 08:14 UTC, GSemikozov commented on components/card/card.css
> +.card__image > img {
селекторы тегов и вложенные селекторы в БЭМ не используем. Как вариант - 2 класса: .card__preview + .card__image

2022-08-22 08:14 UTC, GSemikozov commented on components/card/card.css
> +    height: 100%;
здесь либо фиксированную высоту использовать чтобы место для превью во всех картах было одинаковое, либо (или вместе с тем) - flex-grow: 1, чтобы заголовок всегда отодвигался вниз картчоки

2022-08-22 12:48 UTC, GSemikozov requested changes

2022-08-22 12:48 UTC, GSemikozov commented on components/card/card.css
> +    margin: auto;
лишнее (высоту задали, хотелось бы выравнивать уже внутри?)

2022-08-22 12:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-22 14:05 UTC, GSemikozov approved these changes

2022-08-22 14:05 UTC, merged